services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    networks:
      - psql
    env_file: .docker.env
    volumes:
      - ./docker-container/psql:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U wmc -d wmcdb" ]
      interval: 5s
      timeout: 5s
      retries: 10

  remix-app:
    build: .
    restart: unless-stopped
    networks:
      - psql
      - remix_network
    environment:
      - NODE_ENV=production
    volumes:
      - ./docker-container/prisma:/app/prisma
      - ./docker-container/uploads:/app/public/up-profile-pics
    env_file: .docker.env
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    depends_on:
      db:
        condition: service_healthy

  caddy:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - remix_network
    depends_on:
      - remix-app

networks:
  psql:
    driver: bridge
  remix_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
