services:
  remix-app:
    build: .
    restart: unless-stopped
    networks:
      - remix_network
    environment:
      - NODE_ENV=production
    volumes:
      - ./prisma:/app/prisma
    env_file: .env

  caddy:
    image: caddy:2.9.1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - remix_network
    depends_on:
      - remix-app

networks:
  remix_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
